dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: E0vIWx+lpmcJ/xbC9CCNJDHUuhGty9N57tzFFVVgZmeRetLuUwvSxEDOCBw5G6vz7SsmVTp+Mxqq74BvboJWfHspnExTxEZUvFH3IZllMSfXK+/HiXtHzme9q4xrfI4Lkg+7P9TXXmZjcJO9lv2w5v4lkBnHX64Tp0thX4p4xxXcI8rbuCy478BCbmD/9vnkKCG3UlWU5z22JYHMdkTV0wjEQKGXxTV72t4sGGa0ZLDfJR0w7OuCpyCy4wjrZsT7rgfbVQuqB92kHOAFawZ1qmX8NSy/hnGN6R6PaRJGi4706ITq0PWyXDB+Z0FrZHkvkka8wtNsAokQ29o03QTnWTBD6+VGmNpcD0v9Ho8JLaNkwP8PJGctqUVs8zmPLg7BLNo13xlfpJPJw9Q3jsuPblSff35zsOPt4ol9v4zeNiX0plD33QJ+G4/GXJFEq5xnabss9Z5bb0pskzGSa2F79J1wJMjvf7h3uPyHHn2s50dVx8t7R+4AC0SqwhY+wN+ySVupzjUBzFoTxQNHTUWoS3s50p5+fnPQpuDdV22xsOkdT9DrCKR25fp/jIO10Ph+pJSwHZE7FMwU6rM23PbWZwleRlyTivvLf4b0AeXRpUzxNS+FqP4Z4I+emhbSz02VDDtH8DGLizqMOpxH9Hg72Gfl8de7sxFfSRKOM93GgVs=
  - secure: qUZs4nwranENL0INxBnQTJyEeaQVbfNwJQQm7zdKbXQz0oY8HhQeFy1ZbDVOLjgBuuesY0eINk0ZwJygu80ZQfo/t7dpvDaNR6btyrcnnt+NK5kPJcldUyEGwIHadpPACFYGfMdbnQcp8jb/Cx5aJrBpbBnPVnOX01rGvFpSUlIybZB6PEqDNsWi8K9gcxkzebMb5RaleDM9ZnDi2tuaXwjdb5zi1PfmfPF3FgCHv4AOZuB3TsiUmZMMRk1eVAfQiL2JWuwWknG8/8fj/FMBb5LB9oOSXvw/By4bdnru6kKrvzW0S1ekg+W9hauSfcEvnOrWPhPFTfTmwi8HgReB2qBYySKhA6wmQmG6ppIklQxF0g+viwD2qkWHE71HG//FmdRvbK5e3d5PnuzWrmcysmQciwI6ah0WuZqgLUDimYohTY1uBPKYHcVC4TpUQTD4k/5oa1/vuLA7MV9cVDN8HvdmfW5akVrKzY6ANaZk6XwKJPT8+UZ6Jb70v6ttsPEYQut/e8hyFi8EwMi88O0kdxFLcO3aWCGwqRU8oh8yYr0Erluukou7iuj6wtedr4FOSV4PC2tkKhZvyVbujDoejTPW6yaYtIGvuEVyqr0IuUL3bux0O5W3pbLuNHp09pXLBqXZI18R1ZWxNKNBaIzgVdaeWic5O+USvn1KU8WXK/4=
  - secure: t0jE7oAlatYK2//+uZBhF1P9t9zn/xVjj1LWZF0xSyNnmyRliMAg4IFPPQdTgRPo/VLUhz1pe9lmxXrXW+fgQIg9E2xrUYUDAT/iWLfoUqbICwCMPLe6+WmLZxFDaAE6ohg4beN/vimjSrAJZAfJByPUZOiO99IiZpCYTSS6RVbiqFMDdPh6H3HBXktPSJkHYgzOcRNtkMrBbwGb48IkRqfyhGNBfsZWMiMDaiNfH15UsmEi0MljsSalZy0C4D3PQicACdLxicy6Bqzh8PkugzY6EDLOqhBfl8LhTZUSeGazm61s0Rq5M9Xgsqvfm+cflD29ldjVA4ttYVE4eYBy8ZRai6yyhDNiGkyb5lWmaNpBwiyeNKNAsXpHZOPpAISN28FVqVT/PmrxCrUMKcmUpdPXyHkt0HlMvHj7ynzbSH6m7Uq62ks1En+RtD/PYdycY14gKQ76A2RYLM7uteLTKrzf/Ljsc4zaQeqjWq51fT9oLd0ooRTHzBoM2FQjq/s4zge2zi+FtbguJhW4W9vXfwaBnVRKgnCVO66mmmEBbO2l7skMelvL3kmnaBDbPmlYqK1dubCowtKACPBRXIN5rHmHCHlohbJSeB4anr3mtL7cSJ72KELL1ffnd5zBrnvVFJilqVcZ6ZHhci1WGLPVKW8c1vzYZwpFwOCd9CA3N/A=
